var files_dup =
[
    [ "binary_search_simple.c", "binary__search__simple_8c.html", "binary__search__simple_8c" ],
    [ "bubble_sort.c", "bubble__sort_8c.html", "bubble__sort_8c" ],
    [ "bubble_sort_recursive.c", "bubble__sort__recursive_8c.html", "bubble__sort__recursive_8c" ],
    [ "count_1s_sorted_non_increasing_binary_array.c", "count__1s__sorted__non__increasing__binary__array_8c.html", "count__1s__sorted__non__increasing__binary__array_8c" ],
    [ "exponential_search_simple.c", "exponential__search__simple_8c.html", "exponential__search__simple_8c" ],
    [ "find_a_repeating_and_a_missing_number.c", "find__a__repeating__and__a__missing__number_8c.html", "find__a__repeating__and__a__missing__number_8c" ],
    [ "find_first_repeating_element_array_integers.c", "find__first__repeating__element__array__integers_8c.html", "find__first__repeating__element__array__integers_8c" ],
    [ "insertion_sort_iterative.c", "insertion__sort__iterative_8c.html", "insertion__sort__iterative_8c" ],
    [ "insertion_sort_recursive.c", "insertion__sort__recursive_8c.html", "insertion__sort__recursive_8c" ],
    [ "interpolation_search_simple.c", "interpolation__search__simple_8c.html", "interpolation__search__simple_8c" ],
    [ "jump_search_simple.c", "jump__search__simple_8c.html", "jump__search__simple_8c" ],
    [ "largest_three_elements_in_array.c", "largest__three__elements__in__array_8c.html", "largest__three__elements__in__array_8c" ],
    [ "linear_search_sentinel.c", "linear__search__sentinel_8c.html", "linear__search__sentinel_8c" ],
    [ "linear_search_simple.c", "linear__search__simple_8c.html", "linear__search__simple_8c" ],
    [ "merge_sort.c", "merge__sort_8c.html", "merge__sort_8c" ],
    [ "quick_sort.c", "quick__sort_8c.html", "quick__sort_8c" ],
    [ "selection_sort_iterative.c", "selection__sort__iterative_8c.html", "selection__sort__iterative_8c" ],
    [ "selection_sort_recursive.c", "selection__sort__recursive_8c.html", "selection__sort__recursive_8c" ],
    [ "selection_sort_stable.c", "selection__sort__stable_8c.html", "selection__sort__stable_8c" ],
    [ "selection_sort_strings.c", "selection__sort__strings_8c.html", "selection__sort__strings_8c" ],
    [ "simple_sort.c", "simple__sort_8c.html", "simple__sort_8c" ],
    [ "ternary_search_simple.c", "ternary__search__simple_8c.html", "ternary__search__simple_8c" ]
];