name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Environment Info
      run: |
        gcc --version
        uname -a

    - name: Build with Makefile
      run: |
        echo "Running make with LDFLAGS=-lm"
        make LDFLAGS="-lm" VERBOSE=1

    - name: Run Tests
      run: |
        find . -type f -executable -exec {} \;
