name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build with Makefile
      run: |
        make

    - name: Run Tests
      run: |
        for exe in $(find . -type f -executable); do $$exe; done

    - name: Disable Notifications
      if: always()
      continue-on-error: true
      run: echo 'No email notifications for this workflow'
