name: Build, Test, and Document

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Environment Info
      run: |
        gcc --version
        uname -a

    - name: Build with Makefile
      run: |
        echo "Running make with LDFLAGS=-lm"
        make clean
        make LDFLAGS="-lm" CFLAGS="-I. -Wall -Wextra -std=c99"

    - name: Run Tests
      run: |
        find . -type f -executable -exec {} \;

    - name: Install Cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Run Cppcheck
      run: cppcheck --enable=all --inconclusive --std=c99 --language=c --suppress=missingIncludeSystem $(find . -name "*.c")

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Deploy to GitHub Pages
      if: success()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
        cd gh-pages
        rm -rf *
        cp -r ../docs/html/* .
        git add .
        git commit -m "Update documentation"
        git push origin gh-pages
