name: Build, Test, and Document

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Environment Info
      run: |
        gcc --version
        uname -a

    - name: Build with Makefile
      run: |
        echo "Running make with LDFLAGS=-lm"
        make clean
        make LDFLAGS="-lm" CFLAGS="-Iinclude -Wall -Wextra -std=c99"

    - name: Run Tests
      run: |
        find . -type f -executable -exec {} \;

    - name: Run cppcheck
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --inconclusive --std=c99 --language=c --suppress=missingIncludeSystem $(find src include -name "*.c" -o -name "*.h")

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Upload Documentation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: docs/html
        retention-days: 5
